version: '2'

services:
  main-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: vvizard/main-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS:  $RABBITMQ_DEFAULT_PASS
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"