server:
  port: ${SERVER_PORT}
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_PWD}
    keyStoreType: PKCS12

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DB}
      port: ${MONGODB_PORT}
